### ISSUE TITLE
black screen on org.webrtc.SurfaceViewRendere

### ISSUE THREAD

**Issue by HunterPillu** [devjn/WebRTCAndroidFirebase#3]
org.webrtc.SurfaceViewRenderer showing black screen On Android 10 and android 8.1

using latest webrtc sdk version 
implementation 'org.webrtc:google-webrtc:1.0.22512'

Please help

**Comment by thisisnsh** [comment]
@devjn I am also getting the same issue.

**Comment by chiragpatel92** [comment]
I am also getting the same issue. did you find any solution?

**Comment by thisisnsh** [comment]
@chiragpatel92 I was trying to have video call between 2 non-compatible devices. 
try samsung-samsung both android 10. It worked for me. 
also avoid using same internet connection (wifi) on both the devices.

**Comment by devjn** [comment]
It can happen if you are behind the NAT, so you would need Turn server in addition to STUN.
